// Maps semantic image keys to files in /images
// Swap any file in /images and the whole app updates automatically — no code changes needed.
const IMAGES = {
  dealerFamily: "images/dealer-family.jpg",
  trainingPhoto: "images/training-photo.jpg",
  trainingCert: "images/training-cert.jpg",
  athLogo: "images/ath-logo.jpg",
  badge45years: "images/badge-45years.png",
  iconRuler: "images/icon-ruler.jpg",
  americanBuilt: "images/american-built.png",
  badgeMiamiDade: "images/badge-miamidade.png",
  badgeBBB: "images/badge-bbb.jpg",
  badgeSkinCancer: "images/badge-skincancer.jpg",
  reasonsPhoto: "images/reasons-photo.jpg",
  slide9: "images/perfect-day.jpg",
  smartTechTitle: "images/smarttech-title.jpg",
  sensors: "images/sensors.jpg",
  beachBefore: "images/beach-before.jpg",
  beachAfter: "images/beach-after.jpg",
  optFabric: "images/opt-fabric.jpg",
  optArm: "images/opt-arm.jpg",
  optMountWide: "images/opt-mount-wide.jpg",
  optMountClose: "images/opt-mount-close.jpg",
  optDropScreen: "images/opt-dropscreen.jpg",
  fallLoveQ1: "images/falllove-1.jpg",
  fallLoveQ2: "images/falllove-2.jpg",
  fallLoveQ3: "images/falllove-3.jpg",
  fallLoveQ4: "images/falllove-4.jpg",
  award: "images/award.jpg",
  sunestaLogo: "images/sunesta-logo.jpg",
  ledNight: "images/led-night.svg",
  mylinkApp: "images/mylink-app.svg",
  smartTechIllus: "images/smarttech-illus.svg",
  sensorsIllus: "images/sensors-illus.svg",
  fabricSwatches: "images/fabric-swatches.svg",
  serviceBadge: "images/service-badge.svg",
  prodGutter: "images/prod-gutter.svg",
  prodScreen: "images/prod-screen.svg",
  prodLouver: "images/prod-louver.svg",
  prodGutterPhoto: "images/prod-gutter-photo.jpg",
  prodScreenPhoto: "images/prod-screen-photo.jpg",
  prodLouverPhoto: "images/prod-louver-photo.jpg",
  logoGutterHelmet: "images/logo-gutterhelmet.jpg",
  logoEclipse: "images/logo-eclipse.png",
  triAthFamily: "images/tri-ath-family.jpg",
  triSunestaAwning: "images/tri-sunesta-awning.jpg",
};
